### PR TITLE
modesetting: Rotate cursor to match screen

### LINKED ISSUE #1850: Cursor disappears on rotated displays
### Select the version

25.1.X

### Describe your issue

I switched my Void Linux workstation from xorg-server 21.1.21_1 to RotaryBoot58 xlibre-server 25.1.1_1 and now the mouse cursor is invisible on my second display. It can still click and interact with windows, but I cannot see where it is.

### Steps to reproduce

1. Attach a second DisplayPort monitor to the GPU
2. Run `xrandr --output DP-3 --mode 2560x1440 --rate 120.00 --right-of DP-1 --rotate right`
3. Move cursor to the new screen

### What did you expect?

The mouse cursor should still be visible on both displays.

### Additional Information

I have an Arc A770 with the xe kernel driver and modesetting DDX + VariableRefresh enabled in xorg.conf. I also have a custom cursor theme in LXQt, but it shows up fine on the main monitor and didn't have any trouble with the old xorg-server package.

Image

Wouldn't mind taking a crack at this issue, just not too familiar with the xserver codebase.
Thanks

### Extra fields

- [x] I have checked the existing [issues](https://github.com/X11Libre/xserver/issues)
- [x] I have read the [Contributing Guidelines](https://github.com/X11Libre/xserver/blob/master/CONTRIBUTING.md)
- [x] I'd like to work on this issue

### PR DESCRIPTION
**Pull request by ComputerCraftr**
This should fix #1850 and includes some extra safety checks to avoid reading out of bounds.

I built this with `xbps-src` and installed the package on my PC, everything is working fine with the cursor image and hotspot on a rotated screen.

### CODE REVIEW

File: hw/xfree86/drivers/video/modesetting/drmmode_display.c [hunk 1]
```diff
@@ -2013,30 +2034,69 @@ drmmode_load_cursor_argb_check(xf86CrtcPtr crtc, CARD32 *image)
...
+    int cursor_height = drmmode_cursor.dimensions[idx].height;
 
     /* Get the size of the cursor image buffer */
     int image_width  = ms->cursor_image_width;
     int image_height = ms->cursor_image_height;
+    int src_x = 0;
+    int src_y = 0;
+
+    /* Crop origin matches the core's rotated cursor placement in the cursor image buffer. */
+    switch (crtc->rotation & 0xf) {
```
Comment (stefan11111) [inline hw/xfree86/drivers/video/modesetting/drmmode_display.c:2073]: why the mask?

Comment (cepelinas9000) [reply hw/xfree86/drivers/video/modesetting/drmmode_display.c:2073]: If I remember correctly, it can have RR_Reflect_X (16) & RR_Reflect_Y (32) bits ORed

Comment (stefan11111) [reply hw/xfree86/drivers/video/modesetting/drmmode_display.c:2073]: Do these cases work without any special treatment?

Comment (stefan11111) [reply hw/xfree86/drivers/video/modesetting/drmmode_display.c:2073]: Do these cases work without any special treatment?

Comment (ComputerCraftr) [reply hw/xfree86/drivers/video/modesetting/drmmode_display.c:2073]: I was following the convention in xf86Cursors.c that always masks `(rotation & 0xf)` inside every switch statement. It seems like all of the rotated cursors are part of a single image with different coordinates, so I'm adjusting the x and y offsets to read the correct quadrant.

**Comment by josephcrowell** [comment]
Looking good to me.

**Comment by cepelinas9000** [comment]
@ComputerCraftr  When I tested with xfce I got:
```
Inverted &  Horizontal|vertical reflection -> Mouse cursor gone
Inverted -> Looks good
Rotation left -> Wrong (artifacts)
Rotation right -> Wrong (artifacts)
```
It can be there another bug, 

It  not always shows artifact (sometimes you need change cursor few times), here pictures:
left
right

**Comment by ComputerCraftr** [comment]
@cepelinas9000 Interesting, does the cursor still input clicks underneath the glitchy glyph? That would at least tell us the hotspot coordinates are correct...

I was having an issue with the cursor hotspot inputting clicks roughly 200 pixels above where the glyph was drawn while troubleshooting the offsets. I'll try testing out some other desktop environments and custom cursors in a VM.

**Comment by stefan11111** [comment]
Perhaps we need to transpose the cursor glyph matrix when we're copying it into the cursor buffer?

**Comment by cepelinas9000** [comment]
@stefan11111 this one off topic, it happened to my other xfce session started rotated and with compositor.
it crashes due gbm_bo_unmap. You can see on trace, problem - gbm goes through `ms_do_pageflip` in `pageflip.c`

```gdb
(gdb) bt
#0  u_transfer_helper_transfer_unmap (pctx=0x5555566a0b80, ptrans=0x5555558c99c0) at ../mesa-22.0.1/src/gallium/auxiliary/util/u_transfer_helper.c:495
#1  0x00007ffff61a814e in tc_call_texture_unmap (pipe=<optimized out>, call=<optimized out>, last=<optimized out>) at ../mesa-22.0.1/src/gallium/auxiliary/util/u_threaded_context.c:2500
#2  0x00007ffff61a85f2 in tc_batch_execute (job=job@entry=0x7fffd5531420, gdata=gdata@entry=0x0, thread_index=thread_index@entry=0)
    at ../mesa-22.0.1/src/gallium/auxiliary/util/u_threaded_context.c:211
#3  0x00007ffff61a91db in _tc_sync (tc=tc@entry=0x7fffd5530010, func=<optimized out>, info=<optimized out>) at ../mesa-22.0.1/src/gallium/auxiliary/util/u_threaded_context.c:362
#4  0x00007ffff61aed78 in tc_flush (_pipe=0x7fffd5530010, fence=0x0, flags=1) at ../mesa-22.0.1/src/gallium/auxiliary/util/u_threaded_context.c:2997
#5  0x00007ffff5d62e15 in st_context_flush (stctxi=0x5555566bd000, flags=3, fence=0x0, before_flush_cb=0x0, args=0x7fffffffccc0) at ../mesa-22.0.1/src/mesa/state_tracker/st_manager.c:806
#6  0x00007ffff5c7bb71 in dri_flush (cPriv=<optimized out>, dPriv=<optimized out>, flags=<optimized out>, reason=<optimized out>)
    at ../mesa-22.0.1/src/gallium/frontends/dri/dri_drawable.c:532
#7  0x00007ffff73479f1 in drmmode_bo_destroy (drmmode=0x5555558dcf60, bo=0x7fffffffcdd0) at ../hw/xfree86/drivers/video/modesetting/drmmode_display.c:1019
#8  0x00007ffff7353343 in ms_do_pageflip (screen=0x5555559b39a0, new_front=0x55555694c390, event=0x555556956530, ref_crtc=0x5555559a6e60, async=0,
    pageflip_handler=0x7ffff7353ca1 <ms_present_flip_handler>, pageflip_abort=0x7ffff7353cf4 <ms_present_flip_abort>, log_prefix=0x7ffff7357b56 "Present-flip")
    at ../hw/xfree86/drivers/video/modesetting/pageflip.c:525
#9  0x00007ffff7354269 in ms_present_flip (crtc=0x5555560df5e0, event_id=1, target_msc=356666, pixmap=0x55555694c390, sync_flip=1) at ../hw/xfree86/drivers/video/modesetting/present.c:422
#10 0x000055555565bf58 in present_flip (crtc=0x5555560df5e0, event_id=1, target_msc=356666, pixmap=0x55555694c390, sync_flip=1) at ../present/present_scmd.c:171
#11 0x000055555565ce5c in present_execute (vblank=0x55555694e430, ust=13352676980, crtc_msc=356665) at ../present/present_scmd.c:600
#12 0x000055555565d6ca in present_scmd_pixmap (window=0x5555569408c0, pixmap=0x55555694c390, serial=0, valid=0x0, update=0x55555694bda0, x_off=0, y_off=0, target_crtc=0x5555560df5e0,
    wait_fence=0x0, idle_fence=0x0, acquire_syncobj=0x0, release_syncobj=0x0, acquire_point=0, release_point=0, options=0, target_window_msc=0, divisor=1, remainder=0, notifies=0x0,
    num_notifies=0) at ../present/present_scmd.c:876
#13 0x000055555565889d in present_pixmap (window=0x5555569408c0, pixmap=0x55555694c390, serial=0, valid=0x0, update=0x55555694bda0, x_off=0, y_off=0, target_crtc=0x0, wait_fence=0x0,
    idle_fence=0x0, acquire_syncobj=0x0, release_syncobj=0x0, acquire_point=0, release_point=0, options=0, window_msc=0, divisor=1, remainder=0, notifies=0x0, num_notifies=0)
    at ../present/present.c:257
#14 0x000055555565ac8c in proc_present_pixmap_common (client=0x5555566fce00, req_window=12583637, req_pixmap=12583659, req_serial=0, req_valid=0, req_update=12583653, req_x_off=0,
    req_y_off=0, req_target_crtc=0, req_wait_fence=0, req_idle_fence=0, acquire_syncobj=0x0, release_syncobj=0x0, req_acquire_point=0, req_release_point=0, req_options=0, req_target_msc=0,
    req_divisor=1, req_remainder=0, base_req_size=72, req_notifies=0x5555566f5ccc) at ../present/present_request.c:166
#15 0x000055555565adc1 in proc_present_pixmap (client=0x5555566fce00) at ../present/present_request.c:186
#16 0x000055555565b334 in proc_present_dispatch (client=0x5555566fce00) at ../present/present_request.c:320
#17 0x00005555555c3377 in Dispatch () at ../dix/dispatch.c:566
#18 0x00005555555d307e in dix_main (argc=4, argv=0x7fffffffd568, envp=0x7fffffffd590) at ../dix/main.c:288
#19 0x00005555557bdfea in main (argc=4, argv=0x7fffffffd568, envp=0x7fffffffd590) at ../dix/stubmain.c:34

```

**Comment by cepelinas9000** [comment]
> Perhaps we need to transpose the cursor glyph matrix when we're copying it into the cursor buffer?

From artifact 

> @cepelinas9000 Interesting, does the cursor still input clicks underneath the glitchy glyph? That would at least tell us the hotspot coordinates are correct...
> 
> I was having an issue with the cursor hotspot inputting clicks roughly 200 pixels above where the glyph was drawn while troubleshooting the offsets. I'll try testing out some other desktop environments and custom cursors in a VM.

cursor hotspot feel correct - I will test have free time much later.

> Perhaps we need to transpose the cursor glyph matrix when we're copying it into the cursor buffer?

This artifact not always happening, I needed go back and though cursor few times. But feel it like the cursor glyph needs to be already transformed before touching gpu memory.
